apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app : webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 2    
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: apache
        image: bitnami/apache:latest
        ports:
        - containerPort: 80
