# deploy mysql statefulset in k8s
apiVersion: v1
kind: Secret
metadata:
  name: mysqlpwd
type: Opaque
data:
  password: YWtzaGF5

---
apiVersion: v1 
kind: Service
metadata:
  name: db-mysql
  labels:
    app: db-mysql
spec:
  type: ClusterIP
  selector:
    app: db-mysql
  ports:
  - port: 3386
    protocol: TCP
  ClusterIP: "None"  

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-mysql
spec:
  selector:
    matchLabels:
      app: db-mysql
  serviceName: db-mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: db-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db-mysql
        image: mysql:8
        ports:
        - containerPort: 80
          name: db-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpwd
              key: password 
        - name: MYSQL_DATABASE
          value: "mydb"       
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db-volume
    spec:
      storageClassName: "standard"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  
  
