apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: pvc-webserver
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
---
kind : Pod
apiVersion : v1
metadata:
  name: pod-nginx
spec: 
  volumes:
    - name: server-storage
      persistentVolumeClaim:
        claimName: pvc-webserver
  containers:
    - name: pv-controller
      image: nginx
      ports:
    - containerPort: 80
      name : webserver
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: server-storage



